plugins {
    id 'java'
    id 'war'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'javax.servlet:javax.servlet-api:4.0.1'
    implementation 'javax.servlet.jsp.jstl:javax.servlet.jsp.jstl-api:1.2.0'
    implementation 'org.glassfish:javax.servlet.jsp.jstl:1.2.0'
    compileOnly 'org.apache.tomcat:tomcat-servlet-api:9.0.30'
}

test {
    useJUnitPlatform()
}

war {
    archiveFileName = 'task19.war'
}